name: Desarrollo

# Definimos los servicios que se ejecutarán en los contenedores Docker.
services:
  java:
    image: resenascom:${VERSION:-snapshot}
    ports:
      - "${PUERTO_PRODUCCION:-8080}:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/produccion
      SPRING_DATASOURCE_USERNAME: produser
      SPRING_DATASOURCE_PASSWORD: prodpassword
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:${PUERTO_PRODUCCION}/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: 'produccion'
      POSTGRES_USER: 'produser'
      POSTGRES_PASSWORD: 'prodpassword'
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "produser" ]
      timeout: 20s
      retries: 10
    restart: always
