name: Subida a Producción (Sin Cache Manual)

on:
  push:
    tags: [ "v*" ]

jobs:

  # --------------------- PREPARAR ENTORNO ---------------------
  preparar_entorno:
    concurrency:
      group: produccion
      cancel-in-progress: true
    runs-on: self-hosted
    steps:
      - name: Checkout código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configurar JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          check-latest: false

  # --------------------- COMPILAR CÓDIGO ---------------------
  ejecucion_tests_y_sonarqube:
    needs: preparar_entorno
    runs-on: self-hosted
    steps:
      - name: Establecer versión de proyecto para CI
        env:
          VERSION: ${{ github.ref_type == 'tag' && github.ref_name || 'snapshot' }}
        run: mvn versions:set "-DnewVersion=${{ env.VERSION }}"

      - name: Ejecutar Tests, JaCoCo y enviar a SonarQube
        env:
          MAVEN_OPTS: "-Xmx16g -XX:MaxMetaspaceSize=16G"
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          VERSION: ${{ github.ref_type == 'tag' && github.ref_name || 'snapshot' }}
        run: mvn -T24 clean verify jacoco:report sonar:sonar -Dsonar:sonar:sonar.projectVersion=${VERSION}

  # --------------------- CREAR IMAGEN DOCKER ---------------------
  crear_imagen_docker:
    needs: ejecucion_tests_y_sonarqube
    runs-on: self-hosted
    env:
      VERSION: ${{ github.ref_type == 'tag' && github.ref_name || 'snapshot' }}
    steps:
      - name: Construir imagen Docker con versión dinámica
        run: mvn spring-boot:build-image -DskipTests

  # --------------------- DESPLEGAR EN SERVIDOR ---------------------

  desplegar_en_servidor:
    needs: crear_imagen_docker
    runs-on: self-hosted
    steps:
      - name: Desplegar contenedor en servidor
        env:
          VERSION: ${{ github.ref_type == 'tag' && github.ref_name || 'snapshot' }}
          MAVEN_OPTS: "-Xmx16g -XX:MaxMetaspaceSize=16G"
          PUERTO_PRODUCCION: ${{ secrets.PUERTO_PRODUCCION }}
          COMPOSE_PROJECT_NAME: resenascom-prod
        run: docker compose -f compose-produccion.yaml up -d
